version: 2
jobs:
  build-next: &default
    docker:
      - image: circleci/node:13
    steps:
      - checkout
      - run: yarn
      - run: yarn lint
      - run: yarn test
      - run: cd benchmark && yarn && cd - && yarn benchmark
  build-stable:
    <<: *default
    docker:
      - image: circleci/node:12
  build-10:
    <<: *default
    docker:
      - image: circleci/node:10
  build-8:
    <<: *default
    docker:
      - image: circleci/node:8

workflows:
  version: 2
  versions:
    jobs:
      - build-next
      - build-stable
      - build-10
      - build-8
